### ISSUE TITLE
Broken link on Ronin page

### ISSUE THREAD

**Issue by girardof** [hundredrabbits/100r.co#105]
Hi Rek/Devine, 

There's a broken link on https://100r.co/site/ronin.html. When clicking on `dialect of LISP` I'm redirected to https://wiki.xxiivv.com/site/lain.html instead of https://wiki.xxiivv.com/site/lisp.html

I hope this is the correct place to report this kind of issue 😃

**Comment by rekkabell** [comment]
Yes this is the right place to do that :), thank you for reporting the error, it has been fixed.
