### ISSUE TITLE
Extra newline (firstline) rss.xml

### ISSUE THREAD

**Issue by JZL** [hundredrabbits/100r.co#11]
Hi,

Chrome errors on trying to render the rss.xml page (this also might impact some rss readers)
![image](https://user-images.githubusercontent.com/1739784/62633999-20edb300-b903-11e9-8554-c7ddd83d28cb.png). It looks like the problem is [here](https://github.com/hundredrabbits/100r.co/blob/9c681afcccc2c3f66cc845b1def5896201929753/build/feed.js#L49), where there is an empty line at the start of the backtick. I don't want to submit a PR without testing, though.

![image](https://user-images.githubusercontent.com/1739784/62634109-52667e80-b903-11e9-8cd2-0bd1ec06c04d.png)

Thanks!

**Comment by neauoire** [comment]
Fixed, I hope :)
