### ISSUE TITLE
Broken link: https://100r.co/site/site/home.html

### ISSUE THREAD

**Issue by ccorcos** [hundredrabbits/100r.co#16]

**Comment by neauoire** [comment]
Where did you find this link?

**Comment by ccorcos** [comment]
https://www.patreon.com/posts/nasu-33704782

The `guide` link towards the bottom -- received this as an email

**Comment by neauoire** [comment]
Thank you! Fixed it :)

**Comment by ccorcos** [comment]
Does not appear fixed for me yet.

**Comment by neauoire** [comment]
Sorry, it seems like I made a draft instead of edit, should be good now ^^
