### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by narFnarF** [hundredrabbits/100r.co#18]
Sur votre page Patreon, y'a un lien "gear fail" qui pointe vers: https://100r.co/pages/tools_ecosystem.html

Ça affiche une erreur qui demande de rentrer un ticket ici :)

**Comment by narFnarF** [comment]
En fait y'a plusieurs liens brisé. Un autre: https://100r.co/pages/ronin.html

**Comment by neauoire** [comment]
Ca devrait marcher asteur :)
