### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by absort0** [hundredrabbits/100r.co#19]
Hi there, found a broken link on your website and got incentive from it to report it. The broken link is this `https://100r.co/site/work_station.html` and I followed it from [here](https://100r.co/site/off_the_grid.html#computers_and_software). 

Well, other than that, it's impossible to write something here without saying how impressed I am with all the content you are putting on your website and the work you do on the tools you are deploying. Be safe out there and keep up. Thanks!

Ahh, please let me know if possible when you fix the link.

**Comment by rekkabell** [comment]
We're constantly appending to the website, it's something we enjoy doing a lot :). Glad you like it. Sorry it took so long to get to this.

Fixed the link! Thx for reporting.
