### ISSUE TITLE
Typo in "bits"

### ISSUE THREAD

**Issue by aapeliv** [hundredrabbits/100r.co#20]
"Bits" is spelled as "bites" here (it might be a bit confusing to someone because of resemblance to "bytes"):

https://github.com/hundredrabbits/100r.co/blob/a39f4d1f281277dfb18bc09f2b85b54dbb26ed18/src/categories.c#L732

**Comment by neauoire** [comment]
Oh, nice catch. That was a typo :)
Fixed!
