### ISSUE TITLE
Dotgrid Live button leads to empty page due to the button linking to lowercase dotgrid

### ISSUE THREAD

**Issue by DetonDev** [hundredrabbits/100r.co#24]
On the Dotgrid page, the "Use Dotgrid Live" button links to:
https://hundredrabbits.github.io/dotgrid/
This leads to a 404 page when it should be linking to:
https://hundredrabbits.github.io/Dotgrid/

**Comment by rekkabell** [comment]
Fixed. As it turns out, the link for the Ronin live version was also bad. Thx for reporting it.
