### ISSUE TITLE
Why C?

### ISSUE THREAD

**Issue by chrisalcantara** [hundredrabbits/100r.co#25]
Interesting choice to use C to handle building the page. What was the thinking behind it? Why not write all the pages in HTML?

**Comment by neauoire** [comment]
If we write all the content directly in html, we still need to go through all 50 pages to change the navigation, and copy the content over the RSS, and write all the jump links by hand which is a monumental task. So, we decided to automate a few things using C, it was also a pretext to learn the language.

**Comment by chrisalcantara** [comment]
Thanks. I came across the code and was pretty intrigued by th

**Comment by neauoire** [comment]
Exactly, I also use [plan9](https://wiki.xxiivv.com/site/plan9.html) quite a bit and I wanted to have the option of building the site from it. The only languages supported on the platform at the moment are C and plan9.

**Comment by chrisalcantara** [comment]
What are your thoughts on Go? I started the path to learning C years ago and found Go to be much easier to use. Though, I do like the bare-bones aspect of C. The langauge makes me think. I'm also happy to take this conversation off GitHub.

**Comment by neauoire** [comment]
Go is alright, I like that is abstracts some of the things of C, and make working with strings easier. But the convenience that comes with Go, also has some downside, like you said, you don't have to think as much. Nowadays I mostly do 6502 assembly code, and that really makes me thing and I've learnt to love the pain of having to think again. So I'll stick to C for now, maybe learn some forth in the future :)

This is a fine place, maybe someone else stumbles on this someday looking for the same answers as you.

**Comment by chrisalcantara** [comment]
> Nowadays I mostly do 6502 assembly code, and that really makes me think and I've learnt to love the pain of having to think again. So I'll stick to C for now, maybe learn some forth in the future :)

Very cool. I'm sure you don't want to dive too much into C++, as that's a language with too many features and weight behind it, which probably goes against your ethos of simplicity and functionality.
