### ISSUE TITLE
What happened to Poodle and Moogle?

### ISSUE THREAD

**Issue by pixelheresy** [hundredrabbits/100r.co#32]
Had fun with them a few months back and I can totally find Noodle in the repo and the live site linked from the XXIIVV wiki, but the links for Poodle and Moogle are dead dead dead. 

Hugs from Klövsjö [normally Stockholm],

-k

**Comment by neauoire** [comment]
Poodle has turned into [graf3dscene](https://wiki.xxiivv.com/site/graf3dscene.html), and I've removed Moogle, but I still have a copy around if you need it :)

**Comment by pixelheresy** [comment]
Excellent. Thanks!

I would totally love a copy of Moogle! Direct me to where to get the code and I can take it from there!

**Comment by neauoire** [comment]
I've rebuilt moogle for linux if you're still interested, it's available [here](https://wiki.xxiivv.com/site/moogle.html). I can't find the old web version, sorry :(
