### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by whispy** [hundredrabbits/100r.co#35]
It would be awesome if you could create an RSS feed as an alternative to an email newsletter. Thanks! 

I'm happy to help provide more info about how to set this up.

**Comment by neauoire** [comment]
We already have an RSS feed, but you mean you would like to be able to follow a separate feed for the monthly updates?

**Comment by whispy** [comment]
I was unable to find the RSS feed while browsing on my phone. Can you share the link?

I'm hoping the RSS feed comprises all updates — monthly updates, new site posts, edits to existing posts, etc.

**Comment by neauoire** [comment]
If you add 100r.co to your RSS reader, it should add it automatically.
The direct link to the feed is: https://100r.co/links/rss.xml

We'll start adding the monthly updates to the RSS :)

**Comment by whispy** [comment]
Thanks, I got it added!
