### ISSUE TITLE
"Radio" link on https://100r.co/site/raspberry_pi.html doesn't work

### ISSUE THREAD

**Issue by pierd** [hundredrabbits/100r.co#45]
It leads to https://100r.co/site/the_radio.html but the page doesn't exist.

https://github.com/hundredrabbits/100r.co/blob/54f9fedd199199365bf2734eb97835e573217753/site/raspberry_pi.html#L61

Should it lead to https://100r.co/site/raspberry_pi.html#radio_pi instead?

**Comment by rekkabell** [comment]
Well yes! It should! Fixed it. 

All the Raspberry Pi projects used to link to different pages, and we forgot to change that specific link. Thanks for reporting it.
