### ISSUE TITLE
Duplicate link in https://100r.co/site/resources.html

### ISSUE THREAD

**Issue by Tyruiop** [hundredrabbits/100r.co#54]
In the **Documentary** section, `A Rogue Mariner on the upper Thames` and `The dinghy cruising companion` link to the same youtube video.

Shouldn't `The dinghy cruising companion` be in the **Manuals** section without link?

**Comment by rekkabell** [comment]
Indeed it should, that's a mistake. Moved Dinghy Cruising Companion to manuals.
