### ISSUE TITLE
Broken links in September's entry

### ISSUE THREAD

**Issue by AlainPlusPlus** [hundredrabbits/100r.co#64]
The following links are broken/invalid on https://100r.co/site/log.html#sep2021:

 - GRAPHICAL CALCULATOR
__**a little graphical calculator**__ link  leads to:
`hhttps://twitter.com/hundredrabbits/status/1440841581641097223?s=20`
Replace it with:
`https://twitter.com/hundredrabbits/status/1440841581641097223`
or `https://twitter.com/hundredrabbits/status/1440841581641097223?s=20`

- DEXE
__**Dexe**__ link leads to:
`https://100r.co/site/git.sr.ht/~rabbits/dexe/`
This might be the correct one:
`https://git.sr.ht/~rabbits/dexe/`

**Comment by rekkabell** [comment]
Ahh dumb errors. I should have re-checked those links one by one. Thanks for saying :), now fixed!
