### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by Lislegaard** [hundredrabbits/100r.co#70]
At this page: https://100r.co/site/raspberry_pi.html
Under "Pi Computer"
In the list 
Pimoroni's Blinkt [Blinkt Controls]

The link from "Blinkt Controls" is dead. It is linking to https://github.com/hundredrabbits/blinkt-control which is not working.

**Comment by rekkabell** [comment]
Yea, sorry about that. We no longer have that page up anywhere. Link was removed, thanks for reporting the dead link :>
