### ISSUE TITLE
Suggestion: build.bat

### ISSUE THREAD

**Issue by xoorath** [hundredrabbits/100r.co#74]
For anyone building on windows using [windows subsystem for linux](https://docs.microsoft.com/en-us/windows/wsl/about) seems like a good option.

I've had success building with the following build.bat script

```
pushd "%~dp0"

::  convert line endings
wsl sed -i -e 's/\r$//' build.sh

::  piggy back build.sh
wsl ./build.sh

popd
```

Is such a script and instructions for using WSL of any interest to you? I'm not sure who else may wish to build from Windows other than me. :)

**Comment by neauoire** [comment]
I doubt it'll be practical for others and it will be clutter for us. 
It's better to make a fork if you want to do this.

Are you thinking about making yourself a wiki using the engine?

**Comment by xoorath** [comment]
Just playing with it for inspiration. I'm doing most of my development on linux from WSL now and wanted to check it out.

Going to close this, see you in the toots.
