### ISSUE TITLE
Broken link: "self-published books"

### ISSUE THREAD

**Issue by pvosper** [hundredrabbits/100r.co#94]
In "Summary of changes for December 2023": "News" there is a broken link:

"Wiktopher was released on paperback! Our small collection of _self-published books_ is growing."

The link for "self-published book" is `https://100r.co/site/media/content/inventory/wik_bdn.jpg`

... which leads to the "page you are looking for does not exist".

Thanks - Paul

**Comment by rekkabell** [comment]
its been corrected, forgot to close this :)
